apiVersion: v1
kind: Service
metadata:
  name: weave-scope-app-lb
  labels:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
spec:
  type: LoadBalancer
  ports:
  - name: app
    port: 80
    protocol: TCP
    targetPort: 4040
    #nodePort: 30002
  selector:
    app: weave-scope
    name: weave-scope-app
    weave-cloud-component: scope
    weave-scope-component: app
---
