---
- name: Install Weave Scope.
  hosts: Pisc0
  connection: local
  gather_facts: yes
  vars:
    vm: openshift0

  roles:
    - role: chilcano.weave-scope
      weave_scope:
        action_to_trigger: deploy  # [ deploy | clean ]
        minishift:
          profile: "{{ vm }}"
        openshift:
          admin_usr: "system:admin"
          admin_pwd: anypassword
          hostname: "{{ vm }}"
          project: weave # overwriting namespace (default is 'weave' in version > 1.7.0)
        #repo: https://cloud.weave.works/k8s/scope.yaml # latest for OpenShift
        repo: "{{ role_path }}/files/scope_1.7.1.yaml"
