- name: clean | Removing Weave-Scope
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} delete --namespace weave-scope -f {{ __weavescope.repo }}"
    - "{{ my_oc }} delete project {{ __weavescope.openshift.project }}"
  ignore_errors: yes
