## to do login as 'system:admin' previously

- name: deploy_weave_scope | Check if exists namespace/project 'weave-scope'
  command: "{{ my_oc }} get projects"
  register: openshift_projects

- name: deploy_weave_scope | Defining the Weave-Scope namespace/project regex
  set_fact:
    regex_weave_scope_prj: "{{ __weavescope.openshift.project }}(.+)Active"

- name: deploy_weave_scope | Create new namespace/project 'weave-scope'
  command: "{{ my_oc }} new-project {{ __weavescope.openshift.project }}"
  when: not openshift_projects.stdout | regex_search(regex_weave_scope_prj)

- name: deploy_weave_scope | Switch to namespace/project 'weave-scope'
  command: "{{ my_oc }} project {{ __weavescope.openshift.project }}"
  when: openshift_projects.stdout | regex_search(regex_weave_scope_prj)

- name: deploy_weave_scope | Preparing namespace/project 'weave-scope'
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} adm policy add-cluster-role-to-user cluster-admin -z {{ __weavescope.openshift.project }}"
    - "{{ my_oc }} adm policy add-scc-to-user privileged -z {{ __weavescope.openshift.project }}"
    - "{{ my_oc }} adm policy add-scc-to-user anyuid -z default"

- name: deploy_weave_scope | Install Weave-Scope
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} apply --namespace {{ __weavescope.openshift.project }} -f {{ __weavescope.repo }}"

- name: deploy_weave_scope | Perform 'port-forward' by using the next command
  debug:
    msg:
      - "CMD: oc port-forward -n {{ __weavescope.openshift.project }} $(oc get -n {{ __weavescope.openshift.project }} pod --selector=weave-scope-component=app -o jsonpath='{.items..metadata.name}') 4040 "
      - "URL: http://127.0.0.1:4040 "
