## to do login as 'system:admin' previously

- name: deploy | Check if exists namespace/project 'weave-scope'
  command: "{{ my_oc }} get projects"
  register: openshift_projects

- name: deploy | Defining the Weave-Scope namespace/project regex
  set_fact:
    regex_weave_scope_prj: "{{ __weavescope.openshift.project }}(.+)Active"

- name: deploy | Create new namespace/project 'weave-scope'
  command: "{{ my_oc }} new-project {{ __weavescope.openshift.project }}"
  when: not openshift_projects.stdout | regex_search(regex_weave_scope_prj)

- name: deploy | Switch to namespace/project 'weave-scope'
  command: "{{ my_oc }} project {{ __weavescope.openshift.project }}"
  when: openshift_projects.stdout | regex_search(regex_weave_scope_prj)

- name: deploy | Preparing namespace/project 'weave-scope'
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} adm policy add-cluster-role-to-user cluster-admin -z {{ __weavescope.openshift.project }}"
    - "{{ my_oc }} adm policy add-scc-to-user privileged -z {{ __weavescope.openshift.project }}"
    - "{{ my_oc }} adm policy add-scc-to-user anyuid -z default"

- name: deploy | Install Weave-Scope
  command: "{{ item }}"
  with_items:
    - "{{ my_oc }} apply --namespace {{ __weavescope.openshift.project }} -f {{ __weavescope.repo }}"
